class LDAPConnectionError(Exception):
    """Ошибка подключение к LDAP"""
    ...
